### ISSUE TITLE
Lumen

### ISSUE THREAD

**Issue by K2ouMais** [netojose/laravel-api-explorer#7]
Hi,

is there a way to implement your project into Lumen?

That would be great.

Thanks in advance

**Comment by netojose** [comment]
Hi @K2ouMais !
Yes, I'm working on this feature and I'm almost finishing. The problem is the Lumen has some limitations when retrieving routes information. In a few days, I will bump a new version with Lumen support

**Comment by K2ouMais** [comment]
OK, nice to hear you are working on it.

I will wait till you release, before I have to migrate my API from Lumen to Laravel.

Thank you for the support.
