### ISSUE TITLE
It seems to expect me to have a default controller

### ISSUE THREAD

**Issue by phiter** [netojose/laravel-api-explorer#8]
Hi, I installed it and navigated to the route but it failed.

![image](https://user-images.githubusercontent.com/12252332/70528048-0d11c200-1b2c-11ea-8058-c8354c232a81.png)

I don't have this file, we changed our default installation and the backend team is following an ADR architecture.

Also we're using https://github.com/lorisleiva/laravel-actions so I don't know if that will work well together.

**Comment by netojose** [comment]
Good point @phiter , I'm using this file assuming default Laravel installation has this file. I will load this file from Laravel vendor folder instead of the Laravel installation and solve this. I will fix this today. Thanks!

**Comment by netojose** [comment]
@phiter, bug fixed on 2.0.1 version (already is available). Now, my controller uses the core base controller, instead of application base controller.

Fix here: https://github.com/netojose/laravel-api-explorer/commit/3e6f751fb2b3e37da8a210f51eb7c83dfdff24a4

Thank you for your cooperation!
